### ISSUE TITLE
V4A driver does not install

### ISSUE THREAD

**Issue by ariel-** [Magisk-Modules-Repo/ViPER4AndroidFX#5]
Hi! I have a problem. I uninstalled my old module (v3.4.2) before installing the last version (v4.1) The new version did not come with the drivers installed.

When opening the program (I chose 2.5.0.5 standard in both cases) I get a prompt to install the drivers and then to reboot, however when rebooting the same alert (drivers not installed) appears. The old version didn't ask to install the drivers so I think something broke with the update.

Device: redmi note 4x (mido)
Android: 9 pie

If you need more data just ask, thanks!

**Comment by Zackptg5** [comment]
If you'd check the magisk module folder, you'd see that the drivers are there. You need to read the changelog to see what changed - the open/close workaround is now a volume key option instead of being installed by default.
These kinds of issues should also be kept to the xda thread as many people have already reported/solved this themselves there
